#!/bin/bash

certbot --nginx -n --expand --domains $(ls /etc/nginx/conf.d/ | xargs -I% cat /etc/nginx/conf.d/% | grep server_name | awk '{print $2}' | sort -u | sed 's/;//' | sed ':a;N;$!ba;s/\n/,/g')