# Generated by Django 4.1 on 2022-08-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forwarder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwarding',
            old_name='prefix',
            new_name='subdomain',
        ),
    ]
